const { MessageEmbed } = require('discord.js');

module.exports = {
  name: 'poll',
  description: 'To make a poll.',
  permissions: ['SEND_MESSAGES', 'MANAGE_MESSAGES'],
  type: 1,
  options: [
    {
      name: 'subject',
      description: 'Specify a subdject.',
      required: true,
      type: 'STRING',
    },
    {
      name: 'channel',
      description: 'Specify a channel.',
      required: true,
      type: 'CHANNEL',
    },
    {
      name: 'answers',
      description: 'Specify the number of reactions/answers.',
      required: true,
      type: 'STRING',
    },
  ],

  run: async (client, interaction, args) => {
    const pollContent = interaction.options.getString('subject');
    const pollChannel = interaction.options.getChannel('channel');
    const pollReactions = interaction.options.getString('answers');

    if (isNaN(pollReactions)) {
      interaction.editReply('Please specify a number');
    } else {
      if (pollReactions > 10) {
        return interaction.editReply('The reactions are limited to 10 max.');
      }

      const embed = new MessageEmbed()
          .setDescription(pollContent)
          .setColor('#4D6FFF')
          .setFooter({
            text: `New poll generated by ${interaction.user.tag}`,
            iconURL: interaction.user.avatarURL(),
          })
          .setTimestamp();
      await interaction.editReply({
        content: `✅ » Poll sucessfuly created in <#${pollChannel.id}>`,
        fetchReply: true,
      });
      const selectChannel = client.channels.cache.get(pollChannel.id);
      const poll = await selectChannel.send({ embeds: [embed] });
      const reactions = [
        '1⃣',
        '2⃣',
        '3⃣',
        '4⃣',
        '5⃣',
        '6⃣',
        '7⃣',
        '8⃣',
        '9⃣',
        '🔟',
      ];
      for (let i = 0; i < pollReactions; i++) {
        await poll.react(reactions[i]);
      }
    }
  },
};
